- platform: buienradar
  timeframe: 30
  monitored_conditions:
#  current condition:
    - symbol
    - conditiondetailed
    - temperature
    - windspeed
    - precipitation_forecast_average
    - precipitation_forecast_total
    - irradiance 
# conditions for forecasted data:
    - symbol_1d
    - symbol_2d
    - symbol_3d
    - symbol_4d
    - symbol_5d
    - mintemp_1d
    - mintemp_2d
    - mintemp_3d
    - mintemp_4d
    - mintemp_5d
    - temperature_1d
    - temperature_2d
    - temperature_3d
    - temperature_4d
    - temperature_5d
    - rainchance_1d
    - rainchance_2d
    - rainchance_3d
    - rainchance_4d
    - rainchance_5d
    - sunchance_1d
    - sunchance_2d
    - sunchance_3d
    - sunchance_4d
    - sunchance_5d
    - rain_1d
    - rain_2d
    - rain_3d
    - rain_4d
    - rain_5d
    - conditionexact_1d 
    - condition_1d 
 
#- platform: template
#  sensors:
#    # Buienradar weather forecast
#    forecast_0:
#      friendly_name_template: Toelichting
#      value_template: Min | Max | Regen
#      icon_template: mdi:weather-partlycloudy
#    forecast_1:
#      friendly_name_template: >
#        {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
#        {{ date | timestamp_custom("%A %d %b") }}
#      value_template: >
#        {{states.sensor.br_minimum_temperature_1d.state|round(0)}}°C | {{states.sensor.br_temperature_1d.state|round(0)}}°C | {{states.sensor.br_rainchance_1d.state|round(0)}}%
#      entity_picture_template: >-
#        {{ states.sensor.br_symbol_1d.attributes.entity_picture }}
#    forecast_2:
#      friendly_name_template: >
#        {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
#        {{ date | timestamp_custom("%A %d %b") }}
#      value_template: >
#        {{states.sensor.br_minimum_temperature_2d.state|round(0)}}°C | {{states.sensor.br_temperature_2d.state|round(0)}}°C | {{states.sensor.br_rainchance_2d.state|round(0)}}%
#      entity_picture_template: >-
#        {{ states.sensor.br_symbol_2d.attributes.entity_picture }}
#    forecast_3:
#      friendly_name_template: >
#        {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
#        {{ date | timestamp_custom("%A %d %b") }}
#      value_template: >
#        {{states.sensor.br_minimum_temperature_3d.state|round(0)}}°C | {{states.sensor.br_temperature_3d.state|round(0)}}°C | {{states.sensor.br_rainchance_3d.state|round(0)}}%
#      entity_picture_template: >-
#        {{ states.sensor.br_symbol_3d.attributes.entity_picture }}
#    forecast_4:
#      friendly_name_template: >
#        {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
#        {{ date | timestamp_custom("%A %d %b") }}
#      value_template: >
#        {{states.sensor.br_minimum_temperature_4d.state|round(0)}}°C | {{states.sensor.br_temperature_4d.state|round(0)}}°C | {{states.sensor.br_rainchance_4d.state|round(0)}}%
#      entity_picture_template: >-
#        {{ states.sensor.br_symbol_1d.attributes.entity_picture }}
#    forecast_5:
#      friendly_name_template: >
#        {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
#        {{ date | timestamp_custom("%A %d %b") }}
#      value_template: >
#        {{states.sensor.br_minimum_temperature_5d.state|round(0)}}°C | {{states.sensor.br_temperature_5d.state|round(0)}}°C | {{states.sensor.br_rainchance_5d.state|round(0)}}%
#      entity_picture_template: >-
#        {{ states.sensor.br_symbol_5d.attributes.entity_picture }}
 
#- platform: statistics  ## For smoothing out spikes
#  name: wind_kph_avg
#  entity_id: sensor.pws_wind_kph
#  sampling_size: 3 #Measures every 15 minutes
#  max_age:
#    minutes: 65
#- platform: statistics
#  name: irradiance_avg   ## For smoothing out spikes
#  entity_id: sensor.br_irradiance
#  sampling_size: 3  #Measures every 10 minutes
#  max_age:
#    minutes: 40  

#Darksky

