
---
  # Welcome to my Home Assistant configuration!
  #
  # This config is based on the setup of Frenck
  # be sure to visit his repo for the latest inspirations
  # https://github.com/frenck/home-assistant-config/tree/master/config
  #
  # Basically, each file in the repository does 1 (one, uno, eins)
  # thing only! Click through it, you'll get it pretty fast.
  #
  # The configuration.yaml is only used to bootstrap the system.
  #
homeassistant:
    # Load packages
  packages: !include_dir_named integrations
  