alias: Mark Person as just arrived
trigger:
  - platform: state
    entity_id: device_tracker.telefoonkevin
    from: 'not_home'
    to: 'home'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.kevin_status
      option: Just arrived