alias: Mark Person as extended away
trigger:
  - platform: state
    entity_id: input_select.kevin_status
    to: 'Away'
    for:
      hours: 24
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.kevin_status
      option: Extended away