- alias: "power state on HA startup"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffS20-1/power"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffS20-2/power"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffS20-3/power"
        payload: ""