# Trigger bij de hal zet alle lichten uit.
# naar bed bool wordt geSET zodat verder triggers genegeerd worden
- alias: Naar Bed
  trigger:
    platform: state
    entity_id: binary_sensor.qubino_eettafel_sensor
  condition:
    condition: state
    entity_id: input_boolean.zwave_ready
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.naar_bed
    - service: homeassistant.turn_off
      entity_id: input_boolean.avond_licht_triggered
    - service: homeassistant.turn_off
      entity_id: script.timed_lamp
    - service: scene.turn_on
      entity_id: scene.All_lights_off
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostaat
        temperature: 18.5
      
# Holiday mode zorgt ervoor dat de lichten uitgaan nadat de rolluiken dicht zijn
# naar bed bool wordt geSET zodat verder triggers genegeerd worden
#- alias: Vakantie lampen uit
#  trigger:
#     platform: numeric_state
#     entity_id: sun.sun
#     value_template: '{{ state.attributes.elevation }}'
#     below: -6.5
#  condition:
#    condition: and
#    conditions:
#    - condition: state
#      entity_id: input_boolean.zwave_ready
#      state: 'on'
#    - condition: state
#      entity_id: input_boolean.holiday_mode
#      state: 'on'
#  action:
#    - service: homeassistant.turn_on
#      entity_id: input_boolean.naar_bed
#    - service: homeassistant.turn_off
#      entity_id: input_boolean.avond_licht_triggered
#    - service: homeassistant.turn_off
#      entity_id: script.timed_lamp
#    - service: scene.turn_on
#      entity_id: scene.All_lights_off