# Reset alle BOOL's voor een nieuwe dag
- alias: reset bools at 6am
  trigger:
    platform: time
    at: '6:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.naar_bed
    - service: homeassistant.turn_off
      entity_id: input_boolean.avond_licht_triggered
    - service: homeassistant.turn_off
      entity_id: input_boolean.hot_day
    - service: homeassistant.turn_off
      entity_id: input_boolean.covers_nighttime
      
- alias: reset bools at 16:00h
  trigger:
    platform: time
    at: '16:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.naar_bed