- alias: "Wake-me up using bedroom lights"
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.wakeup_enabled
      state: 'on'
    - condition: or # One of the conditions below must be true
      conditions:
        - condition: state # Will be true when the switch is 'on'
          entity_id: input_boolean.wakeup_weekend
          state: 'on'
        - condition: time # Will be true on weekdays
          weekday:
            - mon
            - tue
            - wed
            - thu
           # - fri
  action:
    - service: light.turn_on
      entity_id: light.slaapkamer # Put the entity of your light or your group here
      data:
        transition: 500 # Transition time in seconds
        brightness: 200